function isAlbionId(id) {
  return /[\w-]{22}/.test(id);
}

function isTrackEntity(entity) {
  return (
    entity && typeof entity.id === "string" && typeof entity.name === "string" && typeof entity.server === "string"
  );
}

function toTrackEntity(entity, server) {
  if (!entity) return entity;

  if (entity.Id && entity.Name) {
    return {
      id: entity.Id,
      name: entity.Name,
      server,
    };
  }

  if (entity.AllianceId && entity.AllianceTag) {
    return {
      id: entity.AllianceId,
      name: entity.AllianceTag,
      server,
    };
  }

  return entity;
}

// Get all victim items, including equipment and inventory, excluding nulls
function getVictimItems(event) {
  const { Equipment, Inventory } = event.Victim;
  return {
    equipment: [
      Equipment.Armor,
      Equipment.Bag,
      Equipment.Cape,
      Equipment.Food,
      Equipment.Head,
      Equipment.MainHand,
      Equipment.Mount,
      Equipment.OffHand,
      Equipment.Potion,
      Equipment.Shoes,
    ].filter((item) => !!item),
    inventory: Inventory.filter((item) => !!item),
  };
}

const transformEventPlayer = (player) => ({
  id: player.Id,
  name: player.Name,
  ip: player.AverageItemPower,
  killFame: player.KillFame,
  deathFame: player.DeathFame,
  guild: player.GuildId
    ? {
        id: player.GuildId,
        name: player.GuildName,
      }
    : null,
  alliance: player.AllianceId
    ? {
        id: player.AllianceId,
        tag: player.AllianceTag,
        name: player.AllianceName,
      }
    : null,
  equipment: player.Equipment,
});

const transformEvent = (event) => ({
  id: event.EventId,
  server: event.server,
  battle: event.BattleId,
  timestamp: event.TimeStamp,
  fame: event.TotalVictimKillFame,
  lootValue: event.lootValue,
  killer: transformEventPlayer(event.Killer),
  victim: transformEventPlayer(event.Victim),
  participants: event.Participants.map(transformEventPlayer),
});

const FAKE_EVENT = {
  numberOfParticipants: 1,
  groupMemberCount: 1,
  EventId: 930177170,
  TimeStamp: "2023-12-04T02:29:04.863000600Z",
  Version: 4,
  Killer: {
    AverageItemPower: 1016.80084,
    Equipment: {
      MainHand: {
        Type: "T5_2H_IRONCLADEDSTAFF",
        Count: 1,
        Quality: 1,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      OffHand: null,
      Head: {
        Type: "T4_HEAD_CLOTH_ROYAL@1",
        Count: 1,
        Quality: 1,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Armor: {
        Type: "T4_ARMOR_LEATHER_SET3@1",
        Count: 1,
        Quality: 2,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Shoes: {
        Type: "T5_SHOES_LEATHER_UNDEAD@1",
        Count: 1,
        Quality: 2,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Bag: null,
      Cape: {
        Type: "T4_CAPE@1",
        Count: 1,
        Quality: 2,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Mount: {
        Type: "T3_MOUNT_HORSE",
        Count: 1,
        Quality: 1,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Potion: {
        Type: "T8_POTION_CLEANSE",
        Count: 2,
        Quality: 0,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Food: null,
    },
    Inventory: [],
    Name: "Moslm",
    Id: "QmQ31HU0SxClToGZKgwAbQ",
    GuildName: "",
    GuildId: "",
    AllianceName: "",
    AllianceId: "",
    AllianceTag: "",
    Avatar: "AVATAR_05",
    AvatarRing: "AVATARRING_ADC_OCT2019",
    DeathFame: 0,
    KillFame: 10932,
    FameRatio: 109320.0,
    LifetimeStatistics: {
      PvE: {
        Total: 0,
        Royal: 0,
        Outlands: 0,
        Avalon: 0,
        Hellgate: 0,
        CorruptedDungeon: 0,
        Mists: 0,
      },
      Gathering: {
        Fiber: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        Hide: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        Ore: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        Rock: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        Wood: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        All: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
      },
      Crafting: {
        Total: 0,
        Royal: 0,
        Outlands: 0,
        Avalon: 0,
      },
      CrystalLeague: 0,
      FishingFame: 0,
      FarmingFame: 0,
      Timestamp: null,
    },
  },
  Victim: {
    AverageItemPower: 943.93335,
    Equipment: {
      MainHand: {
        Type: "T4_MAIN_NATURESTAFF_KEEPER@1",
        Count: 1,
        Quality: 1,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      OffHand: {
        Type: "T4_OFF_TORCH@1",
        Count: 1,
        Quality: 2,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Head: {
        Type: "T4_HEAD_CLOTH_SET1@1",
        Count: 1,
        Quality: 2,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Armor: {
        Type: "T4_ARMOR_LEATHER_SET3@1",
        Count: 1,
        Quality: 3,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Shoes: {
        Type: "T4_SHOES_GATHERER_HIDE@1",
        Count: 1,
        Quality: 1,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Bag: {
        Type: "T4_BAG@1",
        Count: 1,
        Quality: 3,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Cape: {
        Type: "T4_CAPE@1",
        Count: 1,
        Quality: 2,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Mount: {
        Type: "T3_MOUNT_HORSE",
        Count: 1,
        Quality: 2,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      Potion: null,
      Food: null,
    },
    Inventory: [
      {
        Type: "T4_SHOES_CLOTH_SET1@1",
        Count: 1,
        Quality: 2,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      {
        Type: "T4_POTION_COOLDOWN",
        Count: 3,
        Quality: 0,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      {
        Type: "TREASURE_RITUAL_RARITY1",
        Count: 1,
        Quality: 0,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      {
        Type: "T4_RUNE",
        Count: 1,
        Quality: 0,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      {
        Type: "TREASURE_DECORATIVE_RARITY2",
        Count: 1,
        Quality: 0,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      {
        Type: "T5_RUNE",
        Count: 1,
        Quality: 0,
        ActiveSpells: [],
        PassiveSpells: [],
        LegendarySoul: null,
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    Name: "CafePuroo",
    Id: "YBNm2z4pQf6QoOPXzoI7OQ",
    GuildName: "",
    GuildId: "",
    AllianceName: "",
    AllianceId: "",
    AllianceTag: "",
    Avatar: "AVATAR_03",
    AvatarRing: "AVATARRING_ADC_JUL2019",
    DeathFame: 10932,
    KillFame: 0,
    FameRatio: 0.0,
    LifetimeStatistics: {
      PvE: {
        Total: 0,
        Royal: 0,
        Outlands: 0,
        Avalon: 0,
        Hellgate: 0,
        CorruptedDungeon: 0,
        Mists: 0,
      },
      Gathering: {
        Fiber: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        Hide: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        Ore: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        Rock: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        Wood: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        All: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
      },
      Crafting: {
        Total: 0,
        Royal: 0,
        Outlands: 0,
        Avalon: 0,
      },
      CrystalLeague: 0,
      FishingFame: 0,
      FarmingFame: 0,
      Timestamp: null,
    },
  },
  TotalVictimKillFame: 10932,
  Location: null,
  Participants: [
    {
      AverageItemPower: 1016.80084,
      Equipment: {
        MainHand: {
          Type: "T5_2H_IRONCLADEDSTAFF",
          Count: 1,
          Quality: 1,
          ActiveSpells: [],
          PassiveSpells: [],
          LegendarySoul: null,
        },
        OffHand: null,
        Head: {
          Type: "T4_HEAD_CLOTH_ROYAL@1",
          Count: 1,
          Quality: 1,
          ActiveSpells: [],
          PassiveSpells: [],
          LegendarySoul: null,
        },
        Armor: {
          Type: "T4_ARMOR_LEATHER_SET3@1",
          Count: 1,
          Quality: 2,
          ActiveSpells: [],
          PassiveSpells: [],
          LegendarySoul: null,
        },
        Shoes: {
          Type: "T5_SHOES_LEATHER_UNDEAD@1",
          Count: 1,
          Quality: 2,
          ActiveSpells: [],
          PassiveSpells: [],
          LegendarySoul: null,
        },
        Bag: null,
        Cape: {
          Type: "T4_CAPE@1",
          Count: 1,
          Quality: 2,
          ActiveSpells: [],
          PassiveSpells: [],
          LegendarySoul: null,
        },
        Mount: {
          Type: "T3_MOUNT_HORSE",
          Count: 1,
          Quality: 1,
          ActiveSpells: [],
          PassiveSpells: [],
          LegendarySoul: null,
        },
        Potion: {
          Type: "T8_POTION_CLEANSE",
          Count: 2,
          Quality: 0,
          ActiveSpells: [],
          PassiveSpells: [],
          LegendarySoul: null,
        },
        Food: null,
      },
      Inventory: [],
      Name: "Moslm",
      Id: "QmQ31HU0SxClToGZKgwAbQ",
      GuildName: "",
      GuildId: "",
      AllianceName: "",
      AllianceId: "",
      AllianceTag: "",
      Avatar: "AVATAR_05",
      AvatarRing: "AVATARRING_ADC_OCT2019",
      DeathFame: 0,
      KillFame: 0,
      FameRatio: 0.0,
      LifetimeStatistics: {
        PvE: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
          Hellgate: 0,
          CorruptedDungeon: 0,
          Mists: 0,
        },
        Gathering: {
          Fiber: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          Hide: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          Ore: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          Rock: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          Wood: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          All: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
        },
        Crafting: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        CrystalLeague: 0,
        FishingFame: 0,
        FarmingFame: 0,
        Timestamp: null,
      },
      DamageDone: 2242.0,
      SupportHealingDone: 0.0,
    },
  ],
  GroupMembers: [
    {
      AverageItemPower: 0.0,
      Equipment: {
        MainHand: {
          Type: "T5_2H_IRONCLADEDSTAFF",
          Count: 1,
          Quality: 1,
          ActiveSpells: [],
          PassiveSpells: [],
          LegendarySoul: null,
        },
        OffHand: null,
        Head: null,
        Armor: null,
        Shoes: null,
        Bag: null,
        Cape: null,
        Mount: null,
        Potion: null,
        Food: null,
      },
      Inventory: [],
      Name: "Moslm",
      Id: "QmQ31HU0SxClToGZKgwAbQ",
      GuildName: "",
      GuildId: "",
      AllianceName: "",
      AllianceId: "",
      AllianceTag: "",
      Avatar: "AVATAR_05",
      AvatarRing: "AVATARRING_ADC_OCT2019",
      DeathFame: 0,
      KillFame: 10932,
      FameRatio: 109320.0,
      LifetimeStatistics: {
        PvE: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
          Hellgate: 0,
          CorruptedDungeon: 0,
          Mists: 0,
        },
        Gathering: {
          Fiber: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          Hide: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          Ore: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          Rock: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          Wood: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
          All: {
            Total: 0,
            Royal: 0,
            Outlands: 0,
            Avalon: 0,
          },
        },
        Crafting: {
          Total: 0,
          Royal: 0,
          Outlands: 0,
          Avalon: 0,
        },
        CrystalLeague: 0,
        FishingFame: 0,
        FarmingFame: 0,
        Timestamp: null,
      },
    },
  ],
  GvGMatch: null,
  BattleId: 930177170,
  KillArea: "OPEN_WORLD",
  Category: null,
  Type: "KILL",
};

module.exports = {
  FAKE_EVENT,
  getVictimItems,
  isAlbionId,
  isTrackEntity,
  toTrackEntity,
  transformEvent,
};
